license="MPL-2.0"
issueTrackerURL="https://github.com/Delaser/RingWorld/issues"

[[mods]]
modId="ringworld"
version="${mod_version}"
displayName="RingWorld"
displayURL="https://modrinth.com/mod/ringworld"
authors="Delaser"
description='''
Turns the Overworld into a finite, seamless cylindrical ringworld with periodic gameplay and curved rendering.
'''

[[mixins]]
config="ringworld.mixins.json"

[[mixins]]
config="ringworld.client.mixins.json"

[[dependencies.ringworld]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.ringworld]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
