#!/usr/bin/env python3
"""Build and locally stage the exact 1.3/1.21.1 release; never upload."""
from __future__ import annotations

from contextlib import contextmanager
import json
import os
from pathlib import Path
import subprocess
import zipfile

try:
    from scripts import stage_modrinth_release as core
except ModuleNotFoundError:
    import stage_modrinth_release as core

VERSION = '1.3.0+mc1.21.1'
LABEL = '1.3 for Minecraft 1.21.1'
LOADERS = ('fabric', 'neoforge')
DEPLOY = Path('deploy/backport-1.3')


@contextmanager
def release_profile():
    """Keep the historical 26.1.2 stager unchanged outside this exact profile."""
    values = {'ARTIFACT_VERSION': VERSION, 'RELEASE_LABEL': LABEL,
              'PUBLIC_RELEASE_VERSION': {loader: f'1.3.0-{loader}+mc1.21.1' for loader in LOADERS},
              'PUBLIC_RELEASE_NAME': {loader: f'RingWorld 1.3 for Minecraft 1.21.1 ({"Fabric" if loader == "fabric" else "NeoForge"})'
                                      for loader in LOADERS}}
    old = {name: getattr(core, name) for name in values}
    try:
        for name, value in values.items():
            setattr(core, name, value)
        yield
    finally:
        for name, value in old.items():
            setattr(core, name, value)


def verify_named_contract(fabric_named: Path, neoforge: Path) -> dict:
    """Fabric uses intermediary names at runtime; compare the named build output.

    Runtime jars are independently validated. The named Fabric archive and
    both runtime jars are generated by the same mandatory clean dual build.
    No jar path override or cached-artifact staging mode is accepted.
    """
    with zipfile.ZipFile(fabric_named) as fabric, zipfile.ZipFile(neoforge) as neo:
        for archive in (fabric, neo):
            core.validate_archive_paths(archive.namelist())
        entries = set(core.shared_contract_entries(fabric, neo))
        entries.update(name for name in set(fabric.namelist()) & set(neo.namelist())
                       if name.startswith('dev/ringworld/') and name.endswith('.class'))
        for archive in (fabric, neo):
            entries.update(name for name in archive.namelist()
                           if name.startswith('assets/ringworld/') and not name.endswith('/'))
        for name in sorted(entries):
            if name not in fabric.namelist() or name not in neo.namelist():
                raise core.VerificationError(f'Missing named shared contract: {name}')
            if fabric.read(name) != neo.read(name):
                raise core.VerificationError(f'Named shared contract differs: {name}')
    return {'comparison': 'same-build named Fabric/NeoForge byte equality',
            'entries': sorted(entries), 'fabricNamedSha256': core.digest(fabric_named, 'sha256'),
            'neoforgeSha256': core.digest(neoforge, 'sha256')}


def main() -> int:
    root = Path.cwd()
    source = core.current_public_source(root)
    version = subprocess.run(['java', '-version'], capture_output=True, text=True, check=True)
    if core.java_major(version.stderr + version.stdout) != 21:
        raise core.VerificationError('The 1.21.1 release requires Java 21')
    command = [str(root / ('gradlew.bat' if os.name == 'nt' else 'gradlew')),
               'clean', ':neoforge:clean', 'build', ':neoforge:build',
               '--no-daemon', '--no-parallel', '--console=plain']
    subprocess.run(command, check=True)
    if core.current_public_source(root) != source:
        raise core.VerificationError('Source changed during the release build')
    jars = {'fabric': root / f'build/libs/ringworld-{VERSION}.jar',
            'neoforge': root / f'neoforge/build/libs/ringworld-neoforge-{VERSION}.jar'}
    with release_profile():
        configs = {loader: DEPLOY / f'{loader}.json' for loader in LOADERS}
        for loader in LOADERS:
            config = core.read_json(configs[loader])
            core.validate_release_config(config, loader)
            core.validate_runtime_jar(jars[loader], config, (root / 'LICENSE').read_bytes(), loader=loader)
        contract = verify_named_contract(root / f'build/devlibs/ringworld-{VERSION}-dev.jar', jars['neoforge'])
        for loader in LOADERS:
            target = core.stage_release(jars[loader], configs[loader], DEPLOY / 'description.md',
                                        DEPLOY / 'changelog.md', root / 'LICENSE',
                                        root / 'dist/backport', source, loader=loader)
            (target / 'NAMED-SHARED-CONTRACT.json').write_text(json.dumps(contract, indent=2) + '\n')
            print(f'PASS staged {loader}: {target}')
    print('Local staging only; no token read or upload performed.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
